### ISSUE TITLE
Building bug

### ISSUE THREAD

**Issue by Danijel-Enoch** [Jay035/solimax-next-js#2]
<html><head></head><body>

./pages/staking.tsx:82:25
--

<span>Type error: Argument of type 'string' is not assignable to parameter of type 'SetStateAction&lt;undefined&gt;'.</span></body></html>

So i found this bug while building can you fix it

**Comment by Jay035** [comment]
Fixed....yet to make a push though

**Comment by Jay035** [comment]
Updated
